version: '3'
services:
        nginx:
                build:
                        context: ./Nginx
                        dockerfile: ./Dockerfile
                image: nginx-docker
                ports:
                        - "80:80"
                restart: always
                container_name: nginx-docker

        booking-docker:
                build:
                        context: ./Booking
                        dockerfile: ./Dockerfile
                image: booking-docker
                depends_on:
                        - postgres
                        - nginx
                environment:
                        - DB_SERVER=postgres
                        - POSTGRES_DB=test
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWORD=password
                restart: on-failure
                container_name: booking-docker

        desk-docker:
                build:
                        context: ./Desk
                        dockerfile: ./Dockerfile
                image: desk-docker
                depends_on:
                        - postgres
                        - nginx
                environment:
                        - DB_SERVER=postgres
                        - POSTGRES_DB=test
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWORD=password
                restart: on-failure
                container_name: desk-docker

        room-docker:
                build:
                        context: ./Room
                        dockerfile: ./Dockerfile
                image: room-docker
                depends_on:
                        - postgres
                        - nginx
                environment:
                        - DB_SERVER=postgres
                        - POSTGRES_DB=test
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWORD=password
                restart: on-failure
                container_name: room-docker

        postgres:
                image: postgres:latest
                container_name: postgres
                ports:
                        - "5433:5432"
                environment:
                        - POSTGRES_PASSWORD=password
                        - POSTGRES_USER=postgres
                        - POSTGRES_DB=test
                volumes:
                        - ./postgres-data:/var/lib/postgresql/data